pub mod adaptation;
pub mod behavioral_context;
pub mod config;
pub mod errors;
pub mod heuristics;
pub mod inputs;
pub mod interactions;
pub mod limits;
pub mod profile;
pub mod provenance;
pub mod status;
pub mod style;

pub use adaptation::AdaptationState;
pub use behavioral_context::{BehavioralContext, ComposeMode};
pub use config::SoulConfig;
pub use errors::SoulError;
pub use heuristics::DecisionHeuristic;
pub use inputs::{BehaviorInputs, ComposeRequest};
pub use interactions::InteractionEvent;
pub use limits::SoulLimits;
pub use profile::PersonalityProfile;
pub use provenance::ProvenanceReport;
pub use status::{RegistryStanding, StatusSummary};
pub use style::CommunicationStyle;
